<h2><strong>Política de Privacidad</strong></h2>
<h3><strong>Información  General</strong></h3>
<p>  INTER6 GESTION INTEGRAL S.L., sociedad domiciliada en Madrid  (España), constituida en Madrid ante el notario D. Gonzalo de la Mata Posadas,  inscrita en el Registro Mercantil de Madrid al tomo 27.041, folio 62, Sección  8, Hoja M-487271 con C.I.F.: B-85764777, en adelante <strong>RESERVADEPORTIVA.COM,</strong> es la titular del sitio Web ubicado en el dominio <a href="http://www.reservadeportiva.com">www.reservadeportiva.com</a>.<br />
  La política de privacidad que se describe a continuación sólo es  aplicable al presente Sitio Web, entendiendo como tal todas las páginas y  subpáginas incluidas en el dominio www.reservadeportiva.com. declinando <strong>RESERVADEPORTIVA.COM </strong>cualquier  responsabilidad sobre las diferentes políticas de privacidad y protección de  datos de carácter personal que puedan contener los Sitios Web a los cuales  pueda accederse a través de los hipervínculos ubicados en este Sitio Web y no  gestionados directamente por <strong>RESERVADEPORTIVA.COM</strong>.<br />
  <strong>RESERVADEPORTIVA.COM </strong>desea  poner en conocimiento de los usuarios de este Sitio Web que la presente  declaración refleja la política en materia de protección de datos que sigue <strong>RESERVADEPORTIVA.COM</strong>.  Esta política se ha configurado respetando escrupulosamente la normativa  vigente en materia de protección de datos personales, esto es, entre otras, la  Ley Orgánica 15/1999, de 13 de Diciembre, de Protección de Datos de carácter  personal (en adelante LOPD) y el Real Decreto 994/1999, de 11 de Junio, que  aprueba el Reglamento de medidas de seguridad de los ficheros automatizados que  contengan datos de carácter personal (en adelante Reglamento 994/1999).</p>
<h3><strong>Recogida  de datos de carácter personal</strong></h3>
<p><strong>INTER  6 GESTION INTEGRAL S.L.</strong><strong>, empresa propietaria de esta web y Prestador  del Servicio de gestión del </strong><strong>Centro  de Pádel Las Matillas</strong><strong> (</strong>Centro  de Pádel &quot;Las Matillas&quot; C/ la Guardia, 3 28939 Arroyomolinos (Madrid)<strong>), por medido de  RESERVADEPORTIVA.COM ha accedido a los datos de socios del club mediante un  acuerdo con sus propietarios, los cuales</strong><strong> son responsables del fichero</strong><strong>.</strong><br />
  <strong>RESERVADEPORTIVA.COM </strong>no  recaba voluntariamente datos de carácter personal de los usuarios de este Sitio  Web. Los únicos datos que se solicitan de los Usuarios son aquello<a name="_GoBack" id="_GoBack"></a>s que el usuario proporciona de forma voluntaria a través de  los diferentes formularios del sitio web. En consecuencia <strong>RESERVADEPORTIVA.COM </strong>sólo  dispondrá de datos personales de aquellos usuarios que voluntariamente quieran  proporcionárselos. Sólo en estos casos en que el Usuario lo desee, y siempre de  forma voluntaria, podrá comunicar sus datos de carácter personal a <strong>RESERVADEPORTIVA.COM</strong>.<br />
  Dichos datos proporcionados voluntariamente por el usuario  podrán ser incorporados a un fichero automatizado, que serán propiedad del club  al cual se prestan los servicios de gestión y mantenimiento del programa. En  consecuencia, el Usuario que voluntariamente proporcione a <strong>RESERVADEPORTIVA.COM </strong>sus  datos personales, acepta expresamente el tratamiento de los mismos, con la  exclusiva finalidad de gestionar su condición de usuario registrado de los  servicio de soporte de <strong>RESERVADEPORTIVA.COM</strong>.<br />
  En cualquier caso, los datos recogidos serán tratados siempre  respetando la normativa vigente en materia de protección de datos de carácter  personal.</p>
<h3><strong>Medidas de seguridad</strong></h3>
<p>  Los datos personales comunicados por el Usuario a <strong>RESERVADEPORTIVA.COM</strong>,  pueden ser almacenados en bases de datos automatizadas o no, cuya titularidad  corresponde en exclusiva al <strong>club al cual  se presta el servicio de gestión y mantenimiento</strong> de la aplicación.  RESERVADEPORTIVA.COM asume todas las medidas de índole técnica, organizativa y  de seguridad que garantizan la confidencialidad, integridad y calidad de la  información contenida en las mismas de acuerdo con lo establecido en la LOPD y  en el Reglamento 994/1999.<br />
La comunicación entre los usuarios y <strong>RESERVADEPORTIVA.COM </strong>no  utiliza un canal seguro, y los datos transmitidos no son cifrados, por lo que  se solicita a los Usuarios que se abstengan de enviar aquellos datos personales  que merezcan la consideración de datos especialmente protegidos en los términos  del artículo 7 de la LOPD, ya que las medidas de seguridad aplicables a un  canal no seguro lo hacen desaconsejable. </p>
<h3><strong>Finalidad  del tratamiento de los datos</strong></h3>
<p>  Los datos de carácter personal que sean comunicados  voluntariamente por el Usuario se destinarán únicamente a la finalidad concreta  de gestionar su condición de usuario registrado del servicio de soporte y serán  tratados con la más absoluta confidencialidad, destinándose únicamente a  aquellas finalidades para las que fueron recabados y de las que expresamente se  informa al Usuario en el momento de su recogida en la presente Política de  Privacidad.<br />
  En conformidad con lo expuesto por la Ley Orgánica de Protección  de Datos (Ley Orgánica 15/99) de carácter personal, sus datos personales se  incluirán en nuestro fichero automatizado. La recogida y tratamiento  automatizado de los datos de carácter personal tiene como finalidad principal la  de recoger los datos básicos para poder realizar y facturar las reservas de  servicios que ofrece mediante este servicio el Centro Deportivo.<br />
  En la web se ofrecen diversos servicios on-line en los que se  requieren datos bancarios para poder efectuar el abono de los mismos. Estos  datos se tramitan a través de un servidor seguro. No obstante, cualquier  transferencia de datos a través de internet supone un riesgo de ser  interceptada. Inter6 Gestión Integral S.L. no garantiza que este hecho no pueda  suceder, por lo que el riesgo lo asume la persona que los envía dichos datos. Lo  que se asegura es INTER6 Gestión Integral S.L. nunca venderá o alquilará dicha  información a otras empresas.</p>
<h3><strong>Cesión  de datos</strong></h3>
<p>  La información recabada en esta web podrá ser utilizada para  enviar correos informativos relacionados única y exclusivamente para fines  relacionados con la actividad del club al cual se presta el servicio, tales  como convocatoria de eventos, oferta de servicios disponibles, información  sobre actividades del club, confirmación de servicios solicitados y todas  aquellas comunicaciones que el club estime oportunas.<br />
  En todos los casos se garantiza, si lo desea, el ejercicio de  los derechos de acceso, cancelación o rectificación de los datos de carácter  personal que forman parte de nuestro fichero. Para ello dirigirá su solicitud a  través del correo electrónico del club o llamando por teléfono al <strong>91 668 79 62</strong> o a través de un correo electrónico a la dirección <strong>direccion@lasmatillas.com</strong></p>