<h2>NORMATIVA DE RESERVA DE PISTAS</h2>
<ol type="1">
  <ol>
    <li>
      <p>EL  HORARIO DE LAS PISTAS, TANTO EN INVIERNO COMO EN VERANO SERA EL ACORDADO POR LA  JUNTA DIRECTIVA Y ESTAR&Aacute; EXPUESTO EN EL TABLON DE ANUNCIOS, JUNTO CON EL  HORARIO DE APERTURA Y CIERRE DE LAS INSTALACIONES.</p>
    </li>
    <li>
      <p>LA  RESERVA YA SEA REALIZADA A TRAV&Eacute;S DE INTERNET O PRESENCIAL, DEBER&Aacute; ESTAR  ABONADA ANTES DE COMENZAR A JUGAR, EN CASO CONTRARIO SE CONFECIONARA EL TICKET  Y SE PASARA EN EL RECIBO DEL MES.</p>
    </li>
    <li>
      <p>LA  RESERVA SER&Aacute; EN BLOQUES DE 1,5 HORAS, TANTO PARA TENIS COMO PARA P&Aacute;DEL.</p>
    </li>
    <li>
      <p>EL  N&Uacute;MERO DE RESERVAS DIARIAS POR USUARIO ATRAV&Eacute;S DE INTERNET EST&Aacute;N LIMITADAS A  1,5 HORAS DE PADEL Y 1,5 HORAS DE TENIS. &nbsp;SI HUBIERA PISTAS LIBRES Y UN SOCIO, QUE YA HUBIERA  AGOTADO EL M&Aacute;XIMO DE RESERVAS DIARIAS, ESTUVIERA INTERESADO EN JUGAR, HA DE  SOLICITARLA &nbsp;EN RECEPCION. </p>
    </li>
    <li>
      <p>ES  OBLIGATORIO INTRODUCIR LOS NOMBRES DE LOS CONTRINCANTES EN EL PROCESO DE  RESERVA POR INTERNET O EN RECECPI&Oacute;N. EN CASO DE QUE LOS CONTRINCANTES NO SEAN  SOCIOS, SE COBRAR&Aacute; UN EXTRA DE 7&euro; POR CADA INVITADO QUE JUEGUE. SOLO PODRAN  PERMANECER EN LA PISTA LOS JUGADORES QUE HAYAN FACILITADO SU NOMBRE (UN M&Aacute;XIMO  DE 4 PERSONAS). EN EL CASO QUE NO CORRESPONDAN LOS NOMBRES FACILITADOS CON LOS  JUGADORES REALES, SERAN CONSIDERADOS COMO INVITADOS, COBRANDO EL EXTRA  CORRESPONDIENTE AL SOCIO QUE REALIZ&Oacute; LA RESERVA. </p>
    </li>
    <li>
      <p>EL  PROCESO DE RESERVA POR INTERNET GENERA UN C&Oacute;DIGO DE SEIS DIGITOS QUE SER&Aacute; EL JUSTIFICANTE DE  QUE SEA HA REALIZADO LA RESERVA. EN CASO DE CONFLICTO, SE RESOLVER&Aacute; HACIA EL  PROPIETARIO DE DICHO C&Oacute;DIGO</p>
    </li>
    <li>
      <p>NINGUN  SOCIO QUE TENGA RESERVADA UNA PISTA, PODRA OCUPAR OTRA, CASO DE JUGAR, PERDERIA  SU RESERVA. </p>
    </li>
    <li>      
      <p>TODAS  LAS PISTAS PUEDEN SER RESERVADAS</p>
    </li>
    <li>
      <p>CUANDO  SE RESERVE DE UN DIA PARA OTRO, SU PRECIO SERA DE 0,60 &euro;.      </p>
    </li>
    <li>
      <p>CADA  24 HORAS EL PRECIO SE INCREMENTARA DE LA RESERVA EN 0,60&euro;      </p>
    </li>
    <li>
      <p>LA  CANCELACI&Oacute;N DE UNA PISTA POR CAUSAS NO JUSTIFICADAS SUPONDR&Aacute; UNA PENALIZACI&Oacute;N  DE 0,60&euro; POR CADA D&Iacute;A QUE HAYA BLOQUEADO LA PISTA.        </p>
    </li>
    <li>
      <p>EL  SOCIO QUE PERMANEZCA 15 MINUTOS DESPU&Eacute;S DE HABER TERMINADO SU HORA DE ALQUILER,  TENDRA QUE PAGAR&nbsp; UNA NUEVA HORA O  FRACCI&Oacute;N DE LA LUZ UTILIZADA.     </p>
    </li>
    <li>
      <p>ERA  EL EMPLEADO DE RECEPCION QUIEN PARA MEJOR APROVECHAMIENTO DE LAS INSTALACIONES  DECIDA QUE PISTA ADJUDICAR. IGUALMENTE CUANDO EXISTA UN TIEMPO DE ESPERA ( POR  LLUVIA, CAMPEONATO ETC.) SERA EL QUIEN DECIDA LA ADJUDICACION, PARA LO CUAL  LLEVARA UNA LISTA.    </p>
    </li>
    <li>
      <p>ESTA  PROHIBIDO&nbsp; LA UTILIZACI&Oacute;N DE LAS PISTAS  EN ROPA DE BA&Ntilde;O Y EN CAMISETAS SIN MANGA. ASIMISMO, ESTA PROHIBIDO&nbsp; PERMANECER&nbsp;  DENTRO DE LAS PISTAS CON ROPA DE CALLE.&nbsp;</p>
    </li>
    <li>
      <p>EL JUGADOR SE OBLIGA A CONSERVAR LAS INSTALACIONES Y LOS ACCESORIOS  ASIGNADOS A LA PISTA, NO PUDIENDO INTRODUCIR EN LAS MISMAS NADA QUE NO ESTE  RELACIONADO CON EL JUEGO.</p>
    </li>
    <li>
      <p>NING&Uacute;N  SOCIO PODRA CEDER LA PISTA A OTRO, SERIA EN RECEPCION QUIEN OTORGAR&Aacute;&nbsp; LA PISTA SEG&Uacute;N LA DEMANDA DE ELLA.      </p>
    </li>
  </ol>
<p>&nbsp;</p>
<p>LA DIRECCION</p>
  <p>Asociaci&oacute;n Recreativa Riogrande</p>