var i18n = $.extend({}, i18n || {}, {
    xgcalendar: {
        dateformat: {
            "fulldaykey": "ddMMyyyy",
            "fulldayshow": "X d yyyy",
            "fulldayvalue": "M/d/yyyy",
            "Md": "W d/M",
            "Md3": "X d",
            "separator": "/",
            "year_index": 2,
            "month_index": 0,
            "day_index": 1,
            "day": "d",
            "dom": "Dom",
            "mon": "Lun",
            "tue": "Mar",
            "wed": "Mie",
            "thu": "Jue",
            "fri": "Vie",
            "sat": "Sab",
            "jan": "Ene",
            "feb": "Feb",
            "mar": "Mar",
            "apr": "Abr",
            "may": "May",
            "jun": "Jun",
            "jul": "Jul",
            "aug": "Ago",
            "sep": "Sep",
            "oct": "Oct",
            "nov": "Nov",
            "dec": "Dic"
        },
        "no_implemented": "No implemented yet",
        "to_date_view": "Click to the view of current date",
        "i_undefined": "Undefined",
        "allday_event": "All day event",
        "repeat_event": "Repeat event",
        "time": "Hora",
        "event": "Curso",
        "location": "Pista",
        "participant": "Participant",
        "get_data_exception": "Exception when getting data",
        "new_event": "Nuevo curso",
        "confirm_delete_event": "Do you confirm to delete this event? ",
        "confrim_delete_event_or_all": "Do you want to all repeat events or only this event? \r\nClick [OK] to delete only this event, click [Cancel] delete all events",
        "data_format_error": "Data format error! ",
        "invalid_title": "Event title can not be blank or contains ($<>)",
        "view_no_ready": "View is not ready",
        "example": "e.g., meeting at room 107",
        "content": "Nombre",
        "create_event": "Crear curso",
        "update_detail": "Ver resumen",
        "click_to_detail": "Ver detalles",
        "i_delete": "Ver detalle",
        "day_plural": "dias",
        "others": "Ver todos (",
        "others2": " mas)",
        "item": ""
    }
});
